/**
 * The wasm binary, addressed by the hash of its contents.
 *
 * # Why the filename carries a hash
 *
 * The binary used to be served at one fixed path, and the stale copy that
 * produced is not a theoretical problem — it cost three debugging detours in
 * one session. It fails in the worst possible way: the app loads, runs, and
 * then rejects perfectly good input, because an *old* build is answering. The
 * symptom (`decode ticket: invalid ticket address json`) points at the ticket,
 * which is fine, rather than at the binary, which is not.
 *
 * Every layer had its own reason to hold the old bytes — Bun's route table
 * captures a `Bun.file` at server start, the browser caches by URL, and a
 * static host in front of `dist/` would too. Chasing each one separately is
 * endless; making the URL change whenever the content changes ends all of them
 * at once, because none of those caches can answer for a URL they have never
 * seen.
 *
 * # No stable alias, deliberately
 *
 * The old path is *not* kept as an alias. A stale reference now 404s, which is
 * loud and immediate, rather than quietly resolving to whatever was there
 * before. Given the failure this replaces, a missing file is the better bug.
 *
 * # Why the URL has a `/wasm/` prefix
 *
 * "404s" is a promise the server has to be able to keep, and at the URL root it
 * could not. The app's SPA catch-all matches every unclaimed path, so a request
 * for a hash the server does not have was answered with `index.html` — which
 * the browser dutifully fed to `WebAssembly.instantiate`, producing `expected
 * magic word 00 61 73 6d, found 3c 21 64 6f` (`3c 21 64 6f` is `<!do`). The
 * prefix gives the binary a route of its own that outranks the catch-all, so a
 * miss can answer for itself.
 */

/** The `web/` directory, so paths below read as they do from a shell there. */
const WEB_ROOT = new URL('../', import.meta.url)

/** Where `cargo task web-wasm` leaves the binary, relative to `web/`. */
export const WASM_SOURCE =
  '../crates/agent-share-wasm-client/dist/web/agent_share_wasm_client_bg.wasm'

/** Module holding the generated path, imported by `src/wasm.ts`. */
const GENERATED = new URL('src/wasm-path.ts', WEB_ROOT)

/** URL directory the binary is served from. See the header. */
export const WASM_DIR = '/wasm'

export interface WasmAsset {
  bytes: Uint8Array
  /** Short content hash. */
  hash: string
  /** Filename including the hash. */
  name: string
  /** Absolute URL path the app fetches. */
  path: string
}

/**
 * Read the wasm and derive its content-addressed name, or `null` if it is not
 * readable right now.
 *
 * The nullable case is not just missing-file pedantry: `cargo task web-wasm`
 * replaces this binary while the dev server is watching it, and for part of
 * that window the path does not resolve. A watcher built on {@link wasmAsset}
 * would take the whole server down on every rebuild.
 */
export async function tryWasmAsset(): Promise<WasmAsset | null> {
  const file = Bun.file(new URL(WASM_SOURCE, WEB_ROOT))
  let bytes: Uint8Array
  try {
    if (!(await file.exists())) return null
    bytes = new Uint8Array(await file.arrayBuffer())
  } catch {
    return null
  }
  // SHA-256 truncated to 12 hex. Not a security boundary — the binary is
  // served from our own origin — just enough that two different builds cannot
  // collide onto one URL.
  const hash = new Bun.CryptoHasher('sha256')
    .update(bytes)
    .digest('hex')
    .slice(0, 12)
  const name = `agent_share_wasm_client_bg.${hash}.wasm`
  return { bytes, hash, name, path: `${WASM_DIR}/${name}` }
}

/**
 * Read the wasm and derive its content-addressed name.
 *
 * Exits rather than throwing when the binary is missing: every caller is a
 * top-level script, and the actionable part is the instruction, not a stack.
 */
export async function wasmAsset(): Promise<WasmAsset> {
  const asset = await tryWasmAsset()
  if (!asset) {
    console.error('wasm missing — run `cargo task web-wasm` first')
    process.exit(1)
  }
  return asset
}

/**
 * The binary as an HTTP response.
 *
 * Shared so the headers are stated once. The cache directive is only safe
 * because of the hash in the URL, and that pairing is easier to keep true in
 * one place than in every server that serves the file.
 */
export function wasmResponse(asset: WasmAsset): Response {
  return new Response(asset.bytes, {
    headers: {
      'content-type': 'application/wasm',
      // Safe to cache hard: the URL changes when the bytes do.
      'cache-control': 'public, max-age=31536000, immutable',
    },
  })
}

/**
 * Write the generated path module, if it changed.
 *
 * Guarded on the contents because `bun --hot` watches `src/`: writing the same
 * text every start would rebuild the app on every start, and writing it in a
 * loop would never settle.
 */
export async function writeWasmPath(asset: WasmAsset): Promise<void> {
  const source = `/**
 * GENERATED by \`scripts/wasm-asset.ts\` — do not edit.
 *
 * The wasm binary's content-addressed path. Regenerated by \`dev.ts\`,
 * \`preview.ts\` and \`build.ts\` before they serve or bundle, so a stale
 * binary cannot be served under a URL the browser has already cached.
 */

export const WASM_PATH = '${asset.path}'
`
  const existing = Bun.file(GENERATED)
  if ((await existing.exists()) && (await existing.text()) === source) return
  await Bun.write(GENERATED, source)
}
