/**
 * GENERATED by `scripts/wasm-asset.ts` — do not edit.
 *
 * The wasm binary's content-addressed path. Regenerated by `dev.ts`,
 * `preview.ts` and `build.ts` before they serve or bundle, so a stale
 * binary cannot be served under a URL the browser has already cached.
 */

export const WASM_PATH = '/agent_share_wasm_client_bg.c2ee66755669.wasm'
